name: rastermap
channels:
  - defaults
dependencies:
  - numba
  - numpy
  - pip 
#  - krb5=1.19.4
# - lz4-c=1.9.4
# =23.1.2
# - pyopenssl=23.0.0
#- pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
    #- pysocks
  - python=3.11.3
    # - python-dateutil
  - qt-main=5.15.2
    #- qt-webengine=5.15.9
  - qtwebkit=5.212
    #- requests
  - matplotlib
  - scikit-learn
  - scipy
    #- setuptools=67.8.0
    #- tbb=2021.8.0
    #- threadpoolctl=2.2.0
    #- tk=8.6.12
    # - toml=0.10.2
    #- tornado
    #- tzdata
    #- urllib3
  - pip:
    - pyqtgraph==0.13.3
    - natsort
    - scanimage-tiff-reader
      #- rastermap>0.1.0
